name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/ssh-ed25519
        chmod 600 ~/.ssh/ssh-ed25519
        ssh-keyscan -H 159.223.225.226 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh root@159.223.225.226 'cd /path/to/your/project && git pull && make run_backend'
